In [1]:
import pandas as pd
import numpy as np

In [2]:
title = pd.read_csv('title.csv')
# product_list.rename(columns={'Unnamed: 0':'item_id'}, inplace=True)
# product_list.rename(columns={'PRDUCT':'title'}, inplace=True)
# title = product_list[['item_id', 'title']]
# title.drop('Unnamed: 0', axis = 1, inplace=True)
title

,Unnamed: 0,user_id,item_id,PRDUCT
0,1,1,1,11종 혼합유산균
1,3,2,2,6년근 홍삼 자신만만 홍삼스틱
2,5,3,3,CosmeHeal HEALTHY WHITE EfferGlow(수출용) (코스메힐 ...
3,8,4,4,네이처드림 혈행에 좋은 알티지 오메가3 골드
4,9,5,5,다니스코 5종혼합유산균 100B
...,...,...,...,...
10545,19995,18,10093,알티지 오메가3 츄어블
10546,19996,7,10094,알티지 오메가3 캡슐
10547,19997,18,10095,알티지 오메가3 트리플
10548,19998,40,10096,알티지 오메가3 프리미엄
10549,19999,18,10096,알티지 오메가3 프리미엄

In [3]:
# fill_append = pd.read_csv('fill_append(one_hot).csv')
# fill_append.rename(columns={'Unnamed: 0':'user_id'}, inplace=True)
# fill_append.columns
fill_append = pd.read_csv('fill_append.csv')
# fill_append.rename(columns={'Unnamed: 0':'user_id'}, inplace=True)
# fill_append['item_id'] = fill_append['user_id']
fill_append

       Unnamed: 0          category    price score
0               0  식품건강식품영양제프로바이오틱스  14,800원   NaN
1               1       식품건강식품홍삼홍삼액  22,490원   4.7
2               2               NaN      NaN   4.7
3               3     식품건강식품영양제오메가3   4,300원   NaN
4               4  식품건강식품영양제프로바이오틱스   7,260원   NaN
...           ...               ...      ...   ...
10545       10545     식품건강식품영양제오메가3  19,600원   4.9
10546       10546     식품건강식품영양제오메가3  44,000원   4.7
10547       10547     식품건강식품영양제오메가3  28,300원   NaN
10548       10548     식품건강식품영양제오메가3  52,500원   4.7
10549       10549     식품건강식품영양제오메가3  52,500원   4.7

[10550 rows x 4 columns]

In [4]:
vectorization_func = pd.read_csv('vectorization_func.csv')
vectorization_func.drop(vectorization_func.columns[1:20], axis=1, inplace=True)
vectorization_func.rename(columns={'Unnamed: 0':'user_id'}, inplace=True)
# vectorization_func

In [5]:
tfidf_func = pd.read_csv('tfidf_func.csv')
# tfidf_func.drop('Unnamed: 0', axis = 1, inplace=True)
tfidf_func.drop(tfidf_func.columns[1:20], axis=1, inplace=True)
tfidf_func.rename(columns={'Unnamed: 0':'item_id'}, inplace=True)
# tfidf_func
# tfidf_func

In [6]:
INTAKE_HINT1 = pd.read_csv("Spare_3.csv")
# INTAKE_HINT1.drop('Unnamed: 0', axis = 1, inplace=True)
# INTAKE_HINT1.rename(columns={'Unnamed: 0':'user_id'}, inplace=True)
INTAKE_HINT1

       Unnamed: 0                                       INTAKE_HINT1
0               0                 ,,,,,,,,,알레르기,,,,,,,,,,,어린이,,,,,,,
1               1              ,,,항응고제,,,,,,알레르기,,,,,,당뇨,,,,,,,,,,,,
2               2                ,,,,,,,,,알레르기,,특이체질,,,,,,,,,,,,,,,,
3               3                    ,,,,,,,,,알레르기,,,,,,,,,,,,,,,,,,
4               4                 ,,,,,,,,,알레르기,,,,,,,,,,,어린이,,,,,,,
...           ...                                                ...
10545       10545     혈압강하제,,,항응고제,항혈소판제,고칼슘혈증,,,,,,,,,,,,,,,,,,,,,,
10546       10546  혈압강하제,,,항응고제,항혈소판제,,,,,알레르기,,,,소화,,,,,,,,,위장,,...
10547       10547     혈압강하제,,,항응고제,항혈소판제,고칼슘혈증,,,,,,,,,,,,,,,,,,,,,,
10548       10548  혈압강하제,,,항응고제,항혈소판제,,,,,알레르기,,특이체질,,,,,,임산부,,,,...
10549       10549          혈압강하제,,,항응고제,항혈소판제,,,,,,,,,,,,,,,,,,,,,,,

[10550 rows x 2 columns]

In [7]:
MAIN_FNCTN = pd.read_csv("Spare_4.csv")
# MAIN_FNCTN.drop('Unnamed: 0', axis = 1, inplace=True)
# MAIN_FNCTN.rename(columns={'Unnamed: 0':'item_id'}, inplace=True)

MAIN_FNCTN

       Unnamed: 0                                         MAIN_FNCTN
0               0  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...
1               1  ,,,,,,,,,,,,,,,,,,,,,,,,,기억,기억력,,,,,,,,,,,,,,,...
2               2  ,,,,,,,,,,,,,,,,,,,,,,,,기능,,,,,,,,,,,,,,,,,,,,...
3               3  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...
4               4  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...
...           ...                                                ...
10545       10545  ,,,,골다공증,,,,,,,,,,,,,,,,,,,,기능,,,,,,,,,,,,,,,,...
10546       10546  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...
10547       10547  ,,,,골다공증,,,,,,,,,,,,,,,,,,,,기능,기억,기억력,,,,,,,,,...
10548       10548  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...
10549       10549  ,,,,,,,,,,,,,,,,,,,,,,,,,기억,기억력,,,,,,,,,,,,,,,...

[10550 rows x 2 columns]

In [8]:
# main_df

main_df = pd.merge(title, MAIN_FNCTN, on='Unnamed: 0')
# total = pd.merge(merge_inner, MAIN_FNCTN, on='user_id')
main_df.drop(main_df.columns[:2], axis=1, inplace=True)
main_df

,item_id,PRDUCT,MAIN_FNCTN
0,1,11종 혼합유산균,",,,,,,,,,,,,,,,,,,,,,,,,,기억,기억력,,,,,,,,,,,,,,,..."
1,2,6년근 홍삼 자신만만 홍삼스틱,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."
2,3,CosmeHeal HEALTHY WHITE EfferGlow(수출용) (코스메힐 ...,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."
3,4,네이처드림 혈행에 좋은 알티지 오메가3 골드,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,나이아신,,,,,,,,..."
4,5,다니스코 5종혼합유산균 100B,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."
...,...,...,...
5442,5256,리얼그램 키즈아연비타민D츄어블,",,,,골다공증,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."
5443,5257,리얼그램 활성엽산B,",,,,,,,,,,,,,,,,,,,,,,,,,기억,기억력,,,,,,,,,,,,,,,..."
5444,5258,리얼닥터 데일리 루테인 아이즈 케어,",,,,골다공증,,,,,,,,,,,,,,,,,,,,기능,기억,기억력,,,,,,,,,..."
5445,5259,리얼닥터 멀티바이오틱스 100억 생유산균,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."
5446,5260,리얼닥터 멀티비타민 123 미네랄,",,,,,,,,,,,,,,,,,,,,,,,,,기억,기억력,,,,,,,,,,,,,,,..."

In [9]:
# ratings_df

ratings_df = pd.merge(title, fill_append, on='Unnamed: 0') 
ratings_df = ratings_df[['user_id', 'item_id', 'score']]
ratings_df

      user_id  item_id score
0           1        1   4.7
1           2        2   NaN
2           3        3   4.8
3           4        4   4.9
4           5        5   4.9
...       ...      ...   ...
5442       16     5256   NaN
5443       16     5257   NaN
5444       73     5258   NaN
5445      109     5259   4.7
5446      106     5260   4.7

[5447 rows x 3 columns]

In [10]:
# tags_df

tags_df = pd.merge(title, INTAKE_HINT1, on='Unnamed: 0') 
tags_df = tags_df[['user_id', 'item_id', 'INTAKE_HINT1']]
tags_df

      user_id  item_id                                       INTAKE_HINT1
0           1        1              ,,,항응고제,,,,,,알레르기,,,,,,당뇨,,,,,,,,,,,,
1           2        2                    ,,,,,,,,,알레르기,,,,,,,,,,,,,,,,,,
2           3        3                    ,,,,,,,,,,,,,,,,,,,,,,,,,,,해당없음
3           4        4                    ,,,,,,,,,알레르기,,,,,,,,,,,,,,,,,,
4           5        5                ,,,,,,,,,알레르기,,특이체질,,,,,,,,,,,,,,,,
...       ...      ...                                                ...
5442       16     5256     혈압강하제,,,항응고제,항혈소판제,고칼슘혈증,,,,,,,,,,,,,,,,,,,,,,
5443       16     5257  혈압강하제,,,항응고제,항혈소판제,,,,,알레르기,,특이체질,,,,,,,,,,,,,,,,
5444       73     5258     혈압강하제,,,항응고제,항혈소판제,고칼슘혈증,,,,,,,,,,,,,,,,,,,,,,
5445      109     5259  혈압강하제,,,항응고제,항혈소판제,,,,,알레르기,,특이체질,,,,,,임산부,,,,...
5446      106     5260          혈압강하제,,,항응고제,항혈소판제,,,,,,,,,,,,,,,,,,,,,,,

[5447 rows x 3 columns]

In [11]:
# tota1 = pd.concat([product_list['PRDUCT'], fill_append, INTAKE_HINT1, MAIN_FNCTN],axis=1)

In [12]:
# total_T = total.T

In [13]:
#total1.set_index('PRDUCT',inplace = True)

In [14]:
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5447 entries, 0 to 5446
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  5447 non-null   int64
 1   item_id  5447 non-null   int64
 2   score    619 non-null    object
dtypes: int64(2), object(1)
memory usage: 170.2+ KB

In [15]:
ratings_df.replace('>5<', '5', inplace=True)
ratings_df.replace('4</', '4', inplace=True)
ratings_df.score.value_counts()

4.8    269
4.7    207
4.9     51
4.6     42
5       28
4.5     12
4.4      3
4.3      3
4        1
3.6      1
3.5      1
3.9      1
Name: score, dtype: int64

In [16]:
ratings_df = ratings_df.astype(float)
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5447 entries, 0 to 5446
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  5447 non-null   float64
 1   item_id  5447 non-null   float64
 2   score    619 non-null    float64
dtypes: float64(3)
memory usage: 170.2 KB

In [17]:
# total["MAIN_FNCTN"] = total["MAIN_FNCTN"].apply(str)

In [18]:
# total["MAIN_FNCTN"][0]
# total.info()

In [19]:
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

## Main을 이용한 main_representation

In [20]:
total_count = len(main_df.index)
total_main = list(set([genre for sublist in list(map(lambda x: x.split(','), main_df['MAIN_FNCTN'])) for genre in sublist]))

In [21]:
print(f"전체 제품 수: {total_count}")
print(f"속성: {total_main}")

전체 제품 수: 5447
속성: ['', '탄수화물', '사과', '제방', '화분', '내용', '월경', '자몽', '헬리', '유산', '아캄', '베타', '추출물', '혈액', '등급', '키토산', '양정', '보호', '운반', '리놀렌산', '보지', '배변', '충치', '운동', '구성', '종자', '지방산', '분비', '세라', '바나', '스파', '글루탐산', '알로에', '흡착', '과민반응', '장내', '장과', '라피노스', '스쿠알렌', '배아', '지구', '인지', '나무', '세포', '정어리', '수분', '녹차', '복합', '버섯', '셀레늄', '적용', '자임', '손상', '배초향', '촉진', '보충', '껍질', '정상', '황기', '크롬', '식물', '면역력', '적응', '시니', '베리', '산소', '관절', '콜레스테롤', '세린', '키토', '엽산', '대두', '웰리', '코팅', '함유', '지아', '아프리카', '염기', '황산', '생성', '청국', '효율', '단백질', '쿠스', '비오틴', '황반', '클로렐라', '유단', '기능', '응고', '밀크', '인해', '비타민', '비오', '보스', '방해', '식품', '스마', '생리', '누스', '테아닌', '흐름', '히알루론산', '칼슘', '홍합', '완화', '불편', '억제', '마그네슘', '오일', '세포분열', '시행일', '니아', '재채기', '산화', '표고', '저하', '인정', '해안', '전립선', '조절', '카르니틴', '피로', '미역', '지구력', '커리', '덱스트린', '제거', '화성', '프로바이오틱스', '유해', '기여', '두운', '바나바', '망고', '경전', '위해', '혈관', '콜라겐', '주정', '레우스', '수환', '상피', '카테킨', '스펙', '사민', '작용', '마리', '흡수', '능력', '구강', '시험', '뿌리', '장균', '우유', '활성', '형성', '대사', '수준', '호로', '기억력', '색소', '로스', '로사', '펩타이드', '과체중', '반응', '영양', '저분자', '수행', '포도', '수국', '스타', '변화', '발달', '혈압', '혈소판', '엽록소', '통한', '꽃봉오리', '토마토', '시나', '타코', '오드', '지력', '레몬', '성분', '점막', '관여', '위험', '응집', '추로', '물질', '에이지', '모로', '체지방', '홍국', '해산', '필수', '이완', '치아', '판토텐산', '농축', '향상', '유익', '항체', '오렌지', '레시틴', '마리아', '리프', '면역', '식후', '섬유', '인삼', '베타카로틴', '항산화', '망간', '지방', '로즈마리', '마늘', '콧물', '혼합', '참당귀', '제물', '차전자', '발효', '크랜베리', '자일리톨', '라피', '고시', '프랑스', '피부', '다시마', '피니', '세노', '마토', '조직', '식이', '태아', '동충하초', '레이', '나이아신', '기타', '카르', '요로', '혈행', '커피', '알콕시글리세롤', '블루베리', '두께', '인체', '리세', '화물', '피크', '항산', '유산균', '열매', '지질', '근육', '홍삼', '국문', '상어', '증가', '보습', '폴리', '제품', '분해', '분이', '번호', '골드', '체액', '근력', '골다공증', '환원', '초록', '표고버섯', '어린이', '합성', '추출', '아누', '균사', '해당없음', '조작', '중성', '화합물', '시모네', '정제', '시아노', '신경', '그린', '타르트', '아미노산', '수면', '자외선', '린지', '영문', '콜린', '여성', '엉겅퀴', '프로폴리스', '도움', '호르몬', '셀렌', '아신', '백가', '허니', '밀도', '원활', '상승', '효모', '성장', '신체', '로부터', '활동', '민들레', '마카', '사이드', '저장', '칼륨', '연골', '소화', '요오드', '브로', '오미자', '활성산소', '원료', '시스테인', '균형', '증식', '열처리', '난소', '사람', '콜리', '천마', '성인', '발생', '알코올', '고유', '리아', '안트라퀴논', '분열', '스페인', '백수', '경관', '상피세포', '석류', '파종', '상태', '홍반', '효소', '배양', '정자', '이용', '긴장', '체내', '호모', '구아검', '젤라틴', '인동덩굴', '혈중', '구리', '자일', '관의', '파크', '해물', '에너지', '관련', '남성', '잔틴', '합계', '전해질', '기억', '증진', '신경과', '은행', '항균', '노화', '알콜', '회화나무', '포스', '분말', '로이', '혈당', '백색', '까마귀쪽나무', '파우더', '나토', '시각', '아연', '유지', '스트레스', '몰리브덴', '필요', '파티', '회복']

In [22]:
print(len(total_main))

395

In [23]:
main_count = dict.fromkeys(total_main)

for each_genre_list in main_df['MAIN_FNCTN']:
    for genre in each_genre_list.split(','):
        if main_count[genre] == None:
            main_count[genre] = 1
        else:
            main_count[genre] = main_count[genre]+1

In [24]:
main_count

{'': 2330456,
 '탄수화물': 1432,
 '사과': 7,
 '제방': 1,
 '화분': 2,
 '내용': 3,
 '월경': 56,
 '자몽': 6,
 '헬리': 4,
 '유산': 1117,
 '아캄': 180,
 '베타': 58,
 '추출물': 859,
 '혈액': 1689,
 '등급': 102,
 '키토산': 8,
 '양정': 3,
 '보호': 1800,
 '운반': 303,
 '리놀렌산': 33,
 '보지': 187,
 '배변': 1455,
 '충치': 1,
 '운동': 11,
 '구성': 199,
 '종자': 4,
 '지방산': 6,
 '분비': 1,
 '세라': 1,
 '바나': 33,
 '스파': 14,
 '글루탐산': 15,
 '알로에': 42,
 '흡착': 10,
 '과민반응': 75,
 '장내': 147,
 '장과': 560,
 '라피노스': 2,
 '스쿠알렌': 1,
 '배아': 1,
 '지구': 124,
 '인지': 45,
 '나무': 17,
 '세포': 2577,
 '정어리': 2,
 '수분': 4,
 '녹차': 66,
 '복합': 59,
 '버섯': 2,
 '셀레늄': 180,
 '적용': 1,
 '자임': 36,
 '손상': 100,
 '배초향': 2,
 '촉진': 23,
 '보충': 7,
 '껍질': 2,
 '정상': 2083,
 '황기': 1,
 '크롬': 105,
 '식물': 1,
 '면역력': 489,
 '적응': 563,
 '시니': 186,
 '베리': 18,
 '산소': 1825,
 '관절': 233,
 '콜레스테롤': 299,
 '세린': 14,
 '키토': 9,
 '엽산': 539,
 '대두': 10,
 '웰리': 5,
 '코팅': 1,
 '함유': 300,
 '지아': 201,
 '아프리카': 1,
 '염기': 42,
 '황산': 2,
 '생성': 1317,
 '청국': 3,
 '효율': 2,
 '단백질': 1231,
 '쿠스': 77,
 '비오틴': 347,
 '황반': 288,
 '클로렐라': 2,
 '유단': 3,
 '기능': 2463,
 '응고': 371,
 '밀크': 126,
 '인해': 314,
 '비타민': 1609,
 '비오': 347,
 '보스': 5,
 '방해': 3,
 '식품': 1,
 '스마': 3,
 '생리': 108,
 '누스': 57,
 '테아닌': 65,
 '흐름': 428,
 '히알루론산': 59,
 '칼슘': 1222,
 '홍합': 3,
 '완화': 118,
 '불편': 56,
 '억제': 1981,
 '마그네슘': 167,
 '오일': 3,
 '세포분열': 1531,
 '시행일': 4,
 '니아': 186,
 '재채기': 1,
 '산화': 1607,
 '표고': 2,
 '저하': 31,
 '인정': 31,
 '해안': 2,
 '전립선': 77,
 '조절': 26,
 '카르니틴': 5,
 '피로': 618,
 '미역': 1,
 '지구력': 123,
 '커리': 1,
 '덱스트린': 48,
 '제거': 5,
 '화성': 48,
 '프로바이오틱스': 425,
 '유해': 2826,
 '기여': 5,
 '두운': 564,
 '바나바': 33,
 '망고': 1,
 '경전': 56,
 '위해': 562,
 '혈관': 2,
 '콜라겐': 13,
 '주정': 30,
 '레우스': 30,
 '수환': 1,
 '상피': 561,
 '카테킨': 2,
 '스펙': 5,
 '사민': 30,
 '작용': 982,
 '마리': 247,
 '흡수': 1746,
 '능력': 3,
 '구강': 70,
 '시험': 1,
 '뿌리': 3,
 '장균': 3,
 '우유': 1,
 '활성': 250,
 '형성': 2012,
 '대사': 1216,
 '수준': 1039,
 '호로': 5,
 '기억력': 612,
 '색소': 288,
 '로스': 5,
 '로사': 1,
 '펩타이드': 15,
 '과체중': 14,
 '반응': 75,
 '영양': 42,
 '저분자': 2,
 '수행': 2,
 '포도': 47,
 '수국': 2,
 '스타': 1,
 '변화': 56,
 '발달': 899,
 '혈압': 59,
 '혈소판': 431,
 '엽록소': 1,
 '통한': 430,
 '꽃봉오리': 1,
 '토마토': 2,
 '시나': 1,
 '타코': 70,
 '오드': 62,
 '지력': 26,
 '레몬': 2,
 '성분': 42,
 '점막': 570,
 '관여': 123,
 '위험': 1235,
 '응집': 431,
 '추로': 4,
 '물질': 42,
 '에이지': 4,
 '모로': 9,
 '체지방': 647,
 '홍국': 16,
 '해산': 1787,
 '필수': 48,
 '이완': 1,
 '치아': 269,
 '판토텐산': 483,
 '농축': 7,
 '향상': 3,
 '유익': 203,
 '항체': 42,
 '오렌지': 9,
 '레시틴': 1,
 '마리아': 57,
 '리프': 3,
 '면역': 2073,
 '식후': 77,
 '섬유': 40,
 '인삼': 2,
 '베타카로틴': 56,
 '항산화': 1572,
 '망간': 212,
 '지방': 1334,
 '로즈마리': 3,
 '마늘': 3,
 '콧물': 1,
 '혼합': 7,
 '참당귀': 4,
 '제물': 3,
 '차전자': 42,
 '발효': 8,
 '크랜베리': 5,
 '자일리톨': 1,
 '라피': 2,
 '고시': 4,
 '프랑스': 2,
 '피부': 862,
 '다시마': 1,
 '피니': 1,
 '세노': 1,
 '마토': 79,
 '조직': 953,
 '식이': 40,
 '태아': 526,
 '동충하초': 2,
 '레이': 5,
 '나이아신': 468,
 '기타': 29,
 '카르': 62,
 '요로': 10,
 '혈행': 435,
 '커피': 16,
 '알콕시글리세롤': 3,
 '블루베리': 5,
 '두께': 1,
 '인체': 7,
 '리세': 4,
 '화물': 1432,
 '피크': 3,
 '항산': 1572,
 '유산균': 1117,
 '열매': 58,
 '지질': 343,
 '근육': 415,
 '홍삼': 77,
 '국문': 212,
 '상어': 3,
 '증가': 1,
 '보습': 207,
 '폴리': 80,
 '제품': 70,
 '분해': 8,
 '분이': 42,
 '번호': 4,
 '골드': 157,
 '체액': 42,
 '근력': 8,
 '골다공증': 1234,
 '환원': 96,
 '초록': 3,
 '표고버섯': 2,
 '어린이': 6,
 '합성': 495,
 '추출': 895,
 '아누': 57,
 '균사': 2,
 '해당없음': 1,
 '조작': 3,
 '중성': 302,
 '화합물': 1,
 '시모네': 15,
 '정제': 11,
 '시아노': 1,
 '신경': 839,
 '그린': 17,
 '타르트': 5,
 '아미노산': 953,
 '수면': 44,
 '자외선': 91,
 '린지': 1,
 '영문': 211,
 '콜린': 2,
 '여성': 113,
 '엉겅퀴': 2,
 '프로폴리스': 64,
 '도움': 4724,
 '호르몬': 113,
 '셀렌': 364,
 '아신': 468,
 '백가': 3,
 '허니': 1,
 '밀도': 288,
 '원활': 1454,
 '상승': 74,
 '효모': 2,
 '성장': 567,
 '신체': 42,
 '로부터': 1836,
 '활동': 1455,
 '민들레': 2,
 '마카': 3,
 '사이드': 2,
 '저장': 42,
 '칼륨': 5,
 '연골': 208,
 '소화': 49,
 '요오드': 62,
 '브로': 3,
 '오미자': 4,
 '활성산소': 5,
 '원료': 25,
 '시스테인': 1039,
 '균형': 46,
 '증식': 1193,
 '열처리': 1,
 '난소': 48,
 '사람': 3,
 '콜리': 30,
 '천마': 4,
 '성인': 15,
 '발생': 1235,
 '알코올': 1,
 '고유': 2,
 '리아': 62,
 '안트라퀴논': 1,
 '분열': 1534,
 '스페인': 1,
 '백수': 7,
 '경관': 527,
 '상피세포': 559,
 '석류': 12,
 '파종': 3,
 '상태': 71,
 '홍반': 1,
 '효소': 142,
 '배양': 6,
 '정자': 4,
 '이용': 1814,
 '긴장': 118,
 '체내': 1146,
 '호모': 1037,
 '구아검': 1,
 '젤라틴': 3,
 '인동덩굴': 1,
 '혈중': 592,
 '구리': 120,
 '자일': 9,
 '관의': 527,
 '파크': 5,
 '해물': 4,
 '에너지': 1557,
 '관련': 1,
 '남성': 8,
 '잔틴': 15,
 '합계': 1,
 '전해질': 4,
 '기억': 612,
 '증진': 620,
 '신경과': 393,
 '은행': 57,
 '항균': 69,
 '노화': 319,
 '알콜': 9,
 '회화나무': 13,
 '포스': 46,
 '분말': 56,
 '로이': 2,
 '혈당': 81,
 '백색': 1,
 '까마귀쪽나무': 1,
 '파우더': 3,
 '나토': 2,
 '시각': 564,
 '아연': 952,
 '유지': 2717,
 '스트레스': 162,
 '몰리브덴': 78,
 '필요': 3251,
 '파티': 14,
 '회복': 2}

In [25]:
for each_genre in main_count:
    main_count[each_genre] = np.log10(total_count/main_count[each_genre])
  
main_count

{'': -2.631283532408433,
 '탄수화물': 0.5802143573012953,
 '사과': 2.891059335258875,
 '제방': 3.736157375273132,
 '화분': 3.435127379609151,
 '내용': 3.2590361205534695,
 '월경': 1.9879693482669316,
 '자몽': 2.9580061248894887,
 '헬리': 3.1340973839451696,
 '유산': 0.688104202157523,
 '아캄': 1.480884870169826,
 '베타': 1.9727293817101947,
 '추출물': 0.8021642114418898,
 '혈액': 0.5085277257021235,
 '등급': 1.7275572035112146,
 '키토산': 2.8330673882811883,
 '양정': 3.2590361205534695,
 '보호': 0.480884870169826,
 '운반': 1.254714746770827,
 '리놀렌산': 2.2176434353952446,
 '보지': 1.464315768736633,
 '배변': 0.573294381951206,
 '충치': 3.736157375273132,
 '운동': 2.694764690114907,
 '구성': 1.4373042988634255,
 '종자': 3.1340973839451696,
 '지방산': 2.9580061248894887,
 '분비': 3.736157375273132,
 '세라': 3.736157375273132,
 '바나': 2.2176434353952446,
 '스파': 2.590029339594894,
 '글루탐산': 2.5600661162174507,
 '알로에': 2.1129080848752317,
 '흡착': 2.736157375273132,
 '과민반응': 1.861096111881432,
 '장내': 1.568840040524956,
 '장과': 0.9879693482669317,
 '라피노스': 3.435127379609151,
 '스쿠알렌': 3.736157375273132,
 '배아': 3.736157375273132,
 '지구': 1.642735690110897,
 '인지': 2.0829448614977886,
 '나무': 2.505708453894858,
 '세포': 0.3250429567222273,
 '정어리': 3.435127379609151,
 '수분': 3.1340973839451696,
 '녹차': 1.9166134397312633,
 '복합': 1.9653053636309878,
 '버섯': 3.435127379609151,
 '셀레늄': 1.480884870169826,
 '적용': 3.736157375273132,
 '자임': 2.179854874505845,
 '손상': 1.736157375273132,
 '배초향': 3.435127379609151,
 '촉진': 2.374429539255539,
 '보충': 2.891059335258875,
 '껍질': 3.435127379609151,
 '정상': 0.4174681053253862,
 '황기': 3.736157375273132,
 '크롬': 1.714968076203194,
 '식물': 3.736157375273132,
 '면역력': 1.0468485161495118,
 '적응': 0.9856489804217858,
 '시니': 1.4666444310552158,
 '베리': 2.480884870169826,
 '산소': 0.4748945064806386,
 '관절': 1.3688014542471132,
 '콜레스테롤': 1.2604861869487023,
 '세린': 2.590029339594894,
 '키토': 2.7819148658338073,
 '엽산': 1.0045686100863933,
 '대두': 2.736157375273132,
 '웰리': 3.0371873709371133,
 '코팅': 3.736157375273132,
 '함유': 1.2590361205534697,
 '지아': 1.4329613178526432,
 '아프리카': 3.736157375273132,
 '염기': 2.1129080848752317,
 '황산': 3.435127379609151,
 '생성': 0.6165716003113483,
 '청국': 3.2590361205534695,
 '효율': 3.435127379609151,
 '단백질': 0.6458993223418157,
 '쿠스': 1.8496666501006502,
 '비오틴': 1.1958279004822583,
 '황반': 1.2767648875139013,
 '클로렐라': 3.435127379609151,
 '유단': 3.2590361205534695,
 '기능': 0.34469296343402883,
 '응고': 1.1667834656580862,
 '밀크': 1.6357868301555691,
 '인해': 1.239227727199917,
 '비타민': 0.5296013311741026,
 '비오': 1.1958279004822583,
 '보스': 3.0371873709371133,
 '방해': 3.2590361205534695,
 '식품': 3.736157375273132,
 '스마': 3.2590361205534695,
 '생리': 1.7027336197861824,
 '누스': 1.9802825196006406,
 '테아닌': 1.9232440186302764,
 '흐름': 1.10471360625996,
 '히알루론산': 1.9653053636309878,
 '칼슘': 0.6490861693665966,
 '홍합': 3.2590361205534695,
 '완화': 1.6642753679670066,
 '불편': 1.9879693482669316,
 '억제': 0.439272899734585,
 '마그네슘': 1.5134409041255488,
 '오일': 3.2590361205534695,
 '세포분열': 0.5511821845748711,
 '시행일': 3.1340973839451696,
 '니아': 1.4666444310552158,
 '재채기': 3.736157375273132,
 '산화': 0.5301414985097875,
 '표고': 3.435127379609151,
 '저하': 2.2447956814388594,
 '인정': 2.2447956814388594,
 '해안': 3.435127379609151,
 '전립선': 1.8496666501006502,
 '조절': 2.3211840273023143,
 '카르니틴': 3.0371873709371133,
 '피로': 0.9451689001843162,
 '미역': 3.736157375273132,
 '지구력': 1.646252263833734,
 '커리': 3.736157375273132,
 '덱스트린': 2.054916137897545,
 '제거': 3.0371873709371133,
 '화성': 2.054916137897545,
 '프로바이오틱스': 1.1077684452228205,
 '유해': 0.28498521776059227,
 '기여': 3.0371873709371133,
 '두운': 0.9848782712897898,
 '바나바': 2.2176434353952446,
 '망고': 3.736157375273132,
 '경전': 1.9879693482669316,
 '위해': 0.9864210597040709,
 '혈관': 3.435127379609151,
 '콜라겐': 2.622214022966295,
 '주정': 2.2590361205534695,
 '레우스': 2.2590361205534695,
 '수환': 3.736157375273132,
 '상피': 0.9871945140169707,
 '카테킨': 3.435127379609151,
 '스펙': 3.0371873709371133,
 '사민': 2.2590361205534695,
 '작용': 0.7440458874861824,
 '마리': 1.3434604220134663,
 '흡수': 0.49411313590358114,
 '능력': 3.2590361205534695,
 '구강': 1.8910593352588752,
 '시험': 3.736157375273132,
 '뿌리': 3.2590361205534695,
 '장균': 3.2590361205534695,
 '우유': 3.736157375273132,
 '활성': 1.3382173666010946,
 '형성': 0.43252939888924224,
 '대사': 0.6512238003364159,
 '수준': 0.7195418277159547,
 '호로': 3.0371873709371133,
 '기억력': 0.9494059531275708,
 '색소': 1.2767648875139013,
 '로스': 3.0371873709371133,
 '로사': 3.736157375273132,
 '펩타이드': 2.5600661162174507,
 '과체중': 2.590029339594894,
 '반응': 1.861096111881432,
 '영양': 2.1129080848752317,
 '저분자': 3.435127379609151,
 '수행': 3.435127379609151,
 '포도': 2.0640595173374146,
 '수국': 3.435127379609151,
 '스타': 3.736157375273132,
 '변화': 1.9879693482669316,
 '발달': 0.7823976835399034,
 '혈압': 1.9653053636309878,
 '혈소판': 1.1016801051124006,
 '엽록소': 3.736157375273132,
 '통한': 1.1026889196935457,
 '꽃봉오리': 3.736157375273132,
 '토마토': 3.435127379609151,
 '시나': 3.736157375273132,
 '타코': 1.8910593352588752,
 '오드': 1.9437656857748782,
 '지력': 2.3211840273023143,
 '레몬': 3.435127379609151,
 '성분': 2.1129080848752317,
 '점막': 0.9802825196006407,
 '관여': 1.646252263833734,
 '위험': 0.6444904176774475,
 '응집': 1.1016801051124006,
 '추로': 3.1340973839451696,
 '물질': 2.1129080848752317,
 '에이지': 3.1340973839451696,
 '모로': 2.7819148658338073,
 '체지방': 0.9252530946044317,
 '홍국': 2.5320373926172075,
 '해산': 0.4840328227674878,
 '필수': 2.054916137897545,
 '이완': 3.736157375273132,
 '치아': 1.306405095270724,
 '판토텐산': 1.05221024452162,
 '농축': 2.891059335258875,
 '향상': 3.2590361205534695,
 '유익': 1.428661337359919,
 '항체': 2.1129080848752317,
 '오렌지': 2.7819148658338073,
 '레시틴': 3.736157375273132,
 '마리아': 1.9802825196006406,
 '리프': 3.2590361205534695,
 '면역': 0.41955807317927124,
 '식후': 1.8496666501006502,
 '섬유': 2.1340973839451696,
 '인삼': 3.435127379609151,
 '베타카로틴': 1.9879693482669316,
 '항산화': 0.539704833569743,
 '망간': 1.4098215143443806,
 '지방': 0.6110015456926019,
 '로즈마리': 3.2590361205534695,
 '마늘': 3.2590361205534695,
 '콧물': 3.736157375273132,
 '혼합': 2.891059335258875,
 '참당귀': 3.1340973839451696,
 '제물': 3.2590361205534695,
 '차전자': 2.1129080848752317,
 '발효': 2.8330673882811883,
 '크랜베리': 3.0371873709371133,
 '자일리톨': 3.736157375273132,
 '라피': 3.435127379609151,
 '고시': 3.1340973839451696,
 '프랑스': 3.435127379609151,
 '피부': 0.8006501094484193,
 '다시마': 3.736157375273132,
 '피니': 3.736157375273132,
 '세노': 3.736157375273132,
 '마토': 1.8385302839826907,
 '조직': 0.7570644746348056,
 '식이': 2.1340973839451696,
 '태아': 1.015171631119393,
 '동충하초': 3.435127379609151,
 '레이': 3.0371873709371133,
 '나이아신': 1.065911522199008,
 '기타': 2.273759377374176,
 '카르': 1.9437656857748782,
 '요로': 2.736157375273132,
 '혈행': 1.0976681183184949,
 '커피': 2.5320373926172075,
 '알콕시글리세롤': 3.2590361205534695,
 '블루베리': 3.0371873709371133,
 '두께': 3.736157375273132,
 '인체': 2.891059335258875,
 '리세': 3.1340973839451696,
 '화물': 0.5802143573012953,
 '피크': 3.2590361205534695,
 '항산': 0.539704833569743,
 '유산균': 0.688104202157523,
 '열매': 1.9727293817101947,
 '지질': 1.2008632552303615,
 '근육': 1.1181092785610394,
 '홍삼': 1.8496666501006502,
 '국문': 1.4098215143443806,
 '상어': 3.2590361205534695,
 '증가': 3.736157375273132,
 '보습': 1.4201870298162143,
 '폴리': 1.8330673882811885,
 '제품': 1.8910593352588752,
 '분해': 2.8330673882811883,
 '분이': 2.1129080848752317,
 '번호': 3.1340973839451696,
 '골드': 1.5402577228638983,
 '체액': 2.1129080848752317,
 '근력': 2.8330673882811883,
 '골다공증': 0.6448422155759092,
 '환원': 1.7538861422335636,
 '초록': 3.2590361205534695,
 '표고버섯': 3.435127379609151,
 '어린이': 2.9580061248894887,
 '합성': 1.0415521763395634,
 '추출': 0.7843343399572201,
 '아누': 1.9802825196006406,
 '균사': 3.435127379609151,
 '해당없음': 3.736157375273132,
 '조작': 3.2590361205534695,
 '중성': 1.2561504323159813,
 '화합물': 3.736157375273132,
 '시모네': 2.5600661162174507,
 '정제': 2.694764690114907,
 '시아노': 3.736157375273132,
 '신경': 0.8123954144444319,
 '그린': 2.505708453894858,
 '타르트': 3.0371873709371133,
 '아미노산': 0.7570644746348056,
 '수면': 2.0927046987869447,
 '자외선': 1.7771159829520384,
 '린지': 3.736157375273132,
 '영문': 1.4118749199754395,
 '콜린': 3.435127379609151,
 '여성': 1.6830789317897124,
 '엉겅퀴': 3.435127379609151,
 '프로폴리스': 1.929977401289245,
 '도움': 0.06184748633165489,
 '호르몬': 1.6830789317897124,
 '셀렌': 1.1750559916240761,
 '아신': 1.065911522199008,
 '백가': 3.2590361205534695,
 '허니': 3.736157375273132,
 '밀도': 1.2767648875139013,
 '원활': 0.573592968750113,
 '상승': 1.8669256555421558,
 '효모': 3.435127379609151,
 '성장': 0.9825743163802255,
 '신체': 2.1129080848752317,
 '로부터': 0.47228469840790843,
 '활동': 0.573294381951206,
 '민들레': 3.435127379609151,
 '마카': 3.2590361205534695,
 '사이드': 3.435127379609151,
 '저장': 2.1129080848752317,
 '칼륨': 3.0371873709371133,
 '연골': 1.4180940403103706,
 '소화': 2.0459612952446182,
 '요오드': 1.9437656857748782,
 '브로': 3.2590361205534695,
 '오미자': 3.1340973839451696,
 '활성산소': 3.0371873709371133,
 '원료': 2.3382173666010946,
 '시스테인': 0.7195418277159547,
 '균형': 2.073399543591558,
 '증식': 0.6595169316027902,
 '열처리': 3.736157375273132,
 '난소': 2.054916137897545,
 '사람': 3.2590361205534695,
 '콜리': 2.2590361205534695,
 '천마': 3.1340973839451696,
 '성인': 2.5600661162174507,
 '발생': 0.6444904176774475,
 '알코올': 3.736157375273132,
 '고유': 3.435127379609151,
 '리아': 1.9437656857748782,
 '안트라퀴논': 3.736157375273132,
 '분열': 0.5503320156601699,
 '스페인': 3.736157375273132,
 '백수': 2.891059335258875,
 '경관': 1.0143467600605856,
 '상피세포': 0.9887455673867087,
 '석류': 2.6569761292255074,
 '파종': 3.2590361205534695,
 '상태': 1.8848990265540568,
 '홍반': 3.736157375273132,
 '효소': 1.5838690308900756,
 '배양': 2.9580061248894887,
 '정자': 3.1340973839451696,
 '이용': 0.47752009254905564,
 '긴장': 1.6642753679670066,
 '체내': 0.6769727576417609,
 '호모': 0.7203786188840912,
 '구아검': 3.736157375273132,
 '젤라틴': 3.2590361205534695,
 '인동덩굴': 3.736157375273132,
 '혈중': 0.9638356685502123,
 '구리': 1.6569761292255072,
 '자일': 2.7819148658338073,
 '관의': 1.0143467600605856,
 '파크': 3.0371873709371133,
 '해물': 3.1340973839451696,
 '에너지': 0.5438687627050117,
 '관련': 3.736157375273132,
 '남성': 2.8330673882811883,
 '잔틴': 2.5600661162174507,
 '합계': 3.736157375273132,
 '전해질': 3.1340973839451696,
 '기억': 0.9494059531275708,
 '증진': 0.9437656857748782,
 '신경과': 1.1417648248977055,
 '은행': 1.9802825196006406,
 '항균': 1.8973082845358769,
 '노화': 1.232366692215951,
 '알콜': 2.7819148658338073,
 '회화나무': 2.622214022966295,
 '포스': 2.073399543591558,
 '분말': 1.9879693482669316,
 '로이': 3.435127379609151,
 '혈당': 1.8276723563944823,
 '백색': 3.736157375273132,
 '까마귀쪽나무': 3.736157375273132,
 '파우더': 3.2590361205534695,
 '나토': 3.435127379609151,
 '시각': 0.9848782712897898,
 '아연': 0.7575204268886577,
 '유지': 0.30206773685524135,
 '스트레스': 1.526642360730501,
 '몰리브덴': 1.8440627725826517,
 '필요': 0.2241404057770054,
 '파티': 2.590029339594894,
 '회복': 3.435127379609151}

In [26]:
# create main representations
main_representation = pd.DataFrame(columns=sorted(total_main), index=main_df.index)
for index, each_row in tqdm(main_df.iterrows()):
    dict_temp = {i: main_count[i] for i in each_row['MAIN_FNCTN'].split(',')}
    row_to_add = pd.DataFrame(dict_temp, index=[index])
    main_representation.update(row_to_add)

main_representation

5447it [01:54, 47.44it/s]

,,경관,경전,고시,고유,골다공증,골드,과민반응,과체중,관련,...,황산,회복,회화나무,효모,효소,효율,흐름,흡수,흡착,히알루론산
0,-2.631284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.104714,NaN,NaN,NaN
1,-2.631284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-2.631284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-2.631284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-2.631284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5442,-2.631284,NaN,NaN,NaN,NaN,0.644842,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.494113,NaN,NaN
5443,-2.631284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5444,-2.631284,NaN,NaN,NaN,NaN,0.644842,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.494113,NaN,NaN
5445,-2.631284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5446,-2.631284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Tag를 이용한 medical Representation

In [27]:
# get unique tag
tag_column = list(map(lambda x: x.split(','), tags_df['INTAKE_HINT1']))
unique_tags = list(set(list(map(lambda x: x.strip(), list([tag for sublist in tag_column for tag in sublist])))))

print(unique_tags)

['', '신장', '임산부', '간 질환', '영·유아', '부정맥치료제', '흡연자', '과량섭취', '영유아', '위장', '특이체질', '고칼슘혈증', '어린이', '알레르기', '해당없음', '게에 알르레기', '항혈소판제', '고지혈증치료제', '혈압강하제', '복부팽만감', '소화', '피부가 황색으로 변할 수 있음', '수유', '카페인', '당뇨', '전문의와 상담', '천식', '알러지', '항응고제']

In [28]:
print(len(tag_column))
print(len(unique_tags))

5447
29

In [29]:
# Compute IDF for tag
total_item_count = len(set(tags_df['item_id']))
# key: tag, value: number of movies with such tag
tag_count_dict = dict.fromkeys(unique_tags)

for each_medical_tag_list in tags_df['INTAKE_HINT1']:
    for tag in each_medical_tag_list.split(","):
        if tag_count_dict[tag.strip()] == None:
            tag_count_dict[tag.strip()] = 1
        else:
            tag_count_dict[tag.strip()] += 1

tag_idf = dict()
for each_tag in tag_count_dict:
    tag_idf[each_tag] = np.log10(total_item_count / tag_count_dict[each_tag])

tag_idf

{'': -1.4105815972832607,
 '신장': 1.0824964871991019,
 '임산부': 0.5460541506252965,
 '간 질환': 3.1189257528257768,
 '영·유아': 1.3573737642615946,
 '부정맥치료제': 2.8178957571617955,
 '흡연자': 1.7915668184394464,
 '과량섭취': 1.3110526208224444,
 '영유아': 1.9080723875108834,
 '위장': 0.9479310507894765,
 '특이체질': 0.574857708475501,
 '고칼슘혈증': 0.7227264057300403,
 '어린이': 0.37287567567350133,
 '알레르기': 0.13642838362806423,
 '해당없음': 1.0415578475416203,
 '게에 알르레기': 3.7209857441537393,
 '항혈소판제': 1.2816530503234764,
 '고지혈증치료제': 2.8178957571617955,
 '혈압강하제': 1.2785059750892904,
 '복부팽만감': 1.5971341031866533,
 '소화': 1.16589129557542,
 '피부가 황색으로 변할 수 있음': 1.3726808811055784,
 '수유': 0.5739280731253792,
 '카페인': 1.2944744827891639,
 '당뇨': 0.9575577505908017,
 '전문의와 상담': 2.0488878862180218,
 '천식': 1.1539593779946786,
 '알러지': 1.8178957571617955,
 '항응고제': 0.7249120896684638}

In [30]:
len(tag_idf.keys())

29

In [31]:
# Create medical representations
tag_representation = pd.DataFrame(columns=sorted(unique_tags), index=list(set(tags_df['item_id'])))
for name, group in tqdm(tags_df.groupby(by='item_id')):
    temp_list = list(map(lambda x: x.split(','), list(group['INTAKE_HINT1'])))
    temp_tag_list = list(set(list(map(lambda x: x.strip(), list([tag for sublist in temp_list for tag in sublist])))))

    dict_temp = {i: tag_idf[i.strip()] for i in temp_tag_list}
    row_to_add = pd.DataFrame(dict_temp, index=[group['item_id'].values[0]])
    tag_representation.update(row_to_add)

tag_representation = tag_representation.sort_index(0)
tag_representation

100%|█████████████████████████████████████████████████████████████████████| 5260/5260 [00:10<00:00, 508.37it/s]
/var/folders/5_/m46vm5f115d6c9gp5dllglxh0000gn/T/ipykernel_11427/75976651.py:11: FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only.
  tag_representation = tag_representation.sort_index(0)

,,간 질환,게에 알르레기,고지혈증치료제,고칼슘혈증,과량섭취,당뇨,복부팽만감,부정맥치료제,소화,...,전문의와 상담,천식,카페인,특이체질,피부가 황색으로 변할 수 있음,항응고제,항혈소판제,해당없음,혈압강하제,흡연자
1,-1.410582,NaN,NaN,NaN,NaN,NaN,0.957558,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.724912,NaN,NaN,NaN,NaN
2,-1.410582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-1.410582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.041558,NaN,NaN
4,-1.410582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,-1.410582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.574858,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5256,-1.410582,NaN,NaN,NaN,0.722726,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.724912,1.281653,NaN,1.278506,NaN
5257,-1.410582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.574858,NaN,0.724912,1.281653,NaN,1.278506,NaN
5258,-1.410582,NaN,NaN,NaN,0.722726,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.724912,1.281653,NaN,1.278506,NaN
5259,-1.410582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.048888,NaN,NaN,0.574858,NaN,0.724912,1.281653,NaN,1.278506,NaN
5260,-1.410582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.724912,1.281653,NaN,1.278506,NaN

In [32]:
main_df.head()

,item_id,PRDUCT,MAIN_FNCTN
0,1,11종 혼합유산균,",,,,,,,,,,,,,,,,,,,,,,,,,기억,기억력,,,,,,,,,,,,,,,..."
1,2,6년근 홍삼 자신만만 홍삼스틱,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."
2,3,CosmeHeal HEALTHY WHITE EfferGlow(수출용) (코스메힐 ...,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."
3,4,네이처드림 혈행에 좋은 알티지 오메가3 골드,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,나이아신,,,,,,,,..."
4,5,다니스코 5종혼합유산균 100B,",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..."

In [33]:
tag_representation.loc[1].dropna()

       -1.410582
당뇨      0.957558
알레르기    0.136428
항응고제    0.724912
Name: 1, dtype: object

In [34]:
tag_representation.loc[2].dropna()

       -1.410582
알레르기    0.136428
Name: 2, dtype: object

In [35]:
print(main_representation.shape)
print(tag_representation.shape)

(5447, 395)
(5260, 29)

## Final mediacl Represenation
- main와 tag로 만들어진 representation을 합쳐서 각 main의 vector로 만든다

In [36]:
medical_representation = pd.concat([main_representation, tag_representation], axis=1).fillna(0)
print(medical_representation.shape)
print(medical_representation.describe())

(5447, 424)
                             경관           경전           고시           고유  \
count  5447.000000  5447.000000  5447.000000  5447.000000  5447.000000
mean     -2.631284     0.098139     0.020438     0.002302     0.001261
std       0.000000     0.299886     0.200549     0.084907     0.065817
min      -2.631284     0.000000     0.000000     0.000000     0.000000
25%      -2.631284     0.000000     0.000000     0.000000     0.000000
50%      -2.631284     0.000000     0.000000     0.000000     0.000000
75%      -2.631284     0.000000     0.000000     0.000000     0.000000
max      -2.631284     1.014347     1.987969     3.134097     3.435127

              골다공증           골드         과민반응          과체중           관련  ...  \
count  5447.000000  5447.000000  5447.000000  5447.000000  5447.000000  ...
mean      0.146087     0.044395     0.025626     0.006657     0.000686  ...
std       0.269954     0.257723     0.216895     0.131151     0.050623  ...
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...
75%       0.000000     0.000000     0.000000     0.000000     0.000000  ...
max       0.644842     1.540258     1.861096     2.590029     3.736157  ...

           전문의와 상담           천식          카페인         특이체질  피부가 황색으로 변할 수 있음  \
count  5447.000000  5447.000000  5447.000000  5447.000000       5447.000000
mean      0.017679     0.077538     0.062739     0.145640          0.054181
std       0.189516     0.288927     0.278015     0.250046          0.267304
min       0.000000     0.000000     0.000000     0.000000          0.000000
25%       0.000000     0.000000     0.000000     0.000000          0.000000
50%       0.000000     0.000000     0.000000     0.000000          0.000000
75%       0.000000     0.000000     0.000000     0.574858          0.000000
max       2.048888     1.153959     1.294474     0.574858          1.372681

              항응고제        항혈소판제         해당없음        혈압강하제          흡연자
count  5447.000000  5447.000000  5447.000000  5447.000000  5447.000000
mean      0.129491     0.064236     0.089489     0.064547     0.027957
std       0.277698     0.279671     0.291917     0.279950     0.222069
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000     0.000000     0.000000
75%       0.000000     0.000000     0.000000     0.000000     0.000000
max       0.724912     1.281653     1.041558     1.278506     1.791567

[8 rows x 424 columns]

## Contents 유사도 평가
- Cosine similarity를 사용

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

def cos_sim_matrix(a, b):
    cos_sim = cosine_similarity(a, b)
    result_df = pd.DataFrame(data=cos_sim, index=[a.index])

    return result_df

In [38]:
print(medical_representation.head())

              경관   경전   고시   고유  골다공증   골드  과민반응  과체중   관련  ...  전문의와 상담   천식  \
0 -2.631284  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0  ...      0.0  0.0
1 -2.631284  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0  ...      0.0  0.0
2 -2.631284  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0  ...      0.0  0.0
3 -2.631284  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0  ...      0.0  0.0
4 -2.631284  0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0  ...      0.0  0.0

   카페인  특이체질  피부가 황색으로 변할 수 있음      항응고제  항혈소판제      해당없음  혈압강하제  흡연자
0  0.0   0.0               0.0  0.000000    0.0  0.000000    0.0  0.0
1  0.0   0.0               0.0  0.724912    0.0  0.000000    0.0  0.0
2  0.0   0.0               0.0  0.000000    0.0  0.000000    0.0  0.0
3  0.0   0.0               0.0  0.000000    0.0  1.041558    0.0  0.0
4  0.0   0.0               0.0  0.000000    0.0  0.000000    0.0  0.0

[5 rows x 424 columns]

In [39]:
cs_df = cos_sim_matrix(medical_representation, medical_representation)
cs_df.head()

,0,1,2,3,4,5,6,7,8,9,...,5437,5438,5439,5440,5441,5442,5443,5444,5445,5446
0,1.000000,0.378561,0.381647,0.358394,0.518869,0.474890,0.322019,0.377653,0.378176,0.393206,...,0.509350,0.470223,0.341074,0.451069,0.390514,0.390514,0.527543,0.407536,0.470223,0.499673
1,0.378561,1.000000,0.470196,0.469764,0.657062,0.586109,0.422877,0.559741,0.431415,0.512618,...,0.700086,0.805067,0.652801,0.863327,0.840605,0.840605,0.819967,0.633439,0.805067,0.853477
2,0.381647,0.470196,1.000000,0.444275,0.644468,0.572108,0.399968,0.469069,0.354309,0.368390,...,0.389180,0.452780,0.292018,0.386192,0.376028,0.376028,0.366796,0.283357,0.452780,0.381786
3,0.358394,0.469764,0.444275,1.000000,0.620840,0.553072,0.653872,0.468637,0.648685,0.522238,...,0.378373,0.437037,0.295328,0.390569,0.380290,0.380290,0.370954,0.286568,0.437037,0.386113
4,0.518869,0.657062,0.644468,0.620840,1.000000,0.868958,0.558924,0.655486,0.495118,0.514796,...,0.543848,0.632724,0.408072,0.539673,0.525469,0.525469,0.512569,0.395968,0.632724,0.533516

In [40]:
cs_df.shape

(5447, 5447)

In [41]:
print(cs_df.shape)
print(cs_df[1].sort_values(ascending=False))

(5447, 5447)
1       1.000000
3786    0.985297
5224    0.960309
3842    0.951433
2792    0.946268
          ...
467     0.216090
5338    0.215684
3068    0.207305
5298    0.199751
3631    0.195435
Name: 1, Length: 5447, dtype: float64

In [42]:
print(main_df.loc[1])
print(main_df.loc[4972])
print(main_df.loc[3142])
print(main_df.loc[2043])
print(main_df.loc[2399])

item_id                                                       2
PRDUCT                                         6년근 홍삼 자신만만 홍삼스틱
MAIN_FNCTN    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...
Name: 1, dtype: object
item_id                                                    4820
PRDUCT                                                락피도 징크 키즈
MAIN_FNCTN    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...
Name: 4972, dtype: object
item_id                                                    3034
PRDUCT                                                   뉴트키즈철분
MAIN_FNCTN    ,,,,,,,,,,,,,,,,,,,,,,,,기능,,,,,,,,,,,,,,,,,,,,...
Name: 3142, dtype: object
item_id                                                    1981
PRDUCT                                    광동 맛있는 활성비타민D3 2000IU
MAIN_FNCTN    ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,...
Name: 2043, dtype: object
item_id                                                    2325
PRDUCT                                                   기력보감스틱
MAIN_FNCTN    ,,,,골다공증,,,,,,,,,,,,,,,,,,,,기능,,,,,,,,,,,,,,,,...
Name: 2399, dtype: object

## 추천시스템의 성능 평가
- 학습셋과 테스트셋을 나눈다.
- 테스트셋에서 예측한 평점과 실제 평점의 RMSE를 구한다.

In [43]:
train_df, test_df = train_test_split(ratings_df, test_size=0.2, random_state=1234)

In [44]:
print(train_df.shape)
print(test_df.shape)

(4357, 3)
(1090, 3)

In [45]:
test_df

      user_id  item_id  score
2240     12.0   2173.0    NaN
3234     73.0   3123.0    NaN
147      31.0    145.0    NaN
3644    174.0   3520.0    NaN
5099     23.0   4942.0    NaN
...       ...      ...    ...
1056     23.0   1044.0    NaN
744      25.0    734.0    NaN
4799      1.0   4648.0    NaN
5227     73.0   5055.0    NaN
948      34.0    937.0    NaN

[1090 rows x 3 columns]

In [46]:
test_df.user_id

2240     12.0
3234     73.0
147      31.0
3644    174.0
5099     23.0
        ...
1056     23.0
744      25.0
4799      1.0
5227     73.0
948      34.0
Name: user_id, Length: 1090, dtype: float64

In [47]:
test_userids = list(set(test_df.user_id.values))
test_userids

[1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 11.0,
 12.0,
 14.0,
 15.0,
 16.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 72.0,
 73.0,
 74.0,
 75.0,
 77.0,
 78.0,
 79.0,
 80.0,
 82.0,
 83.0,
 84.0,
 85.0,
 87.0,
 89.0,
 90.0,
 92.0,
 93.0,
 94.0,
 95.0,
 96.0,
 98.0,
 99.0,
 100.0,
 101.0,
 103.0,
 104.0,
 105.0,
 106.0,
 107.0,
 108.0,
 109.0,
 110.0,
 111.0,
 113.0,
 114.0,
 115.0,
 116.0,
 117.0,
 119.0,
 120.0,
 121.0,
 123.0,
 127.0,
 129.0,
 132.0,
 133.0,
 134.0,
 135.0,
 137.0,
 141.0,
 145.0,
 147.0,
 149.0,
 151.0,
 152.0,
 153.0,
 154.0,
 155.0,
 160.0,
 161.0,
 163.0,
 166.0,
 169.0,
 174.0,
 175.0,
 176.0,
 177.0,
 178.0,
 179.0,
 180.0,
 181.0,
 182.0,
 183.0,
 184.0,
 188.0,
 192.0,
 199.0,
 203.0,
 206.0,
 208.0,
 209.0,
 210.0,
 212.0,
 214.0,
 216.0,
 218.0,
 221.0,
 227.0,
 231.0,
 232.0,
 235.0,
 236.0,
 237.0,
 238.0,
 239.0,
 242.0,
 244.0,
 245.0,
 246.0,
 250.0,
 252.0,
 257.0,
 260.0,
 261.0,
 268.0,
 269.0,
 275.0,
 276.0,
 279.0]

In [48]:
result_df = pd.DataFrame()

for user_id in tqdm(test_userids):
    user_record_df = train_df.loc[train_df.user_id == int(user_id), :]
    
    user_sim_df = cs_df.loc[user_record_df['item_id']]  # (n, 9742); n은 userId가 평점을 매긴 영화 수
    user_rating_df = user_record_df[['score']]  # (n, 1)
    sim_sum = np.sum(user_sim_df.T.to_numpy(), -1)  # (9742, 1)
    # print("user_id=", i, user_record_df.shape, user_sim_df.T.shape, user_rating_df.shape, sim_sum.shape)

    prediction = np.matmul(user_sim_df.T.to_numpy(), user_rating_df.to_numpy()).flatten() / (sim_sum+1) # (9742, 1)

    prediction_df = pd.DataFrame(prediction, index=cs_df.index).reset_index()
    prediction_df.columns = ['item_id', 'pred_rating']    
    prediction_df = prediction_df[['item_id', 'pred_rating']][prediction_df.item_id.isin(test_df[test_df.user_id == user_id]['item_id'].values)]

    temp_df = prediction_df.merge(test_df[test_df.user_id == user_id], on='item_id')
    result_df = pd.concat([result_df, temp_df], axis=0)

100%|███████████████████████████████████████████████████████████████████████| 174/174 [00:00<00:00, 309.50it/s]

In [49]:
result_df.head(10)

   item_id  pred_rating  user_id  score
0        1          NaN      1.0    4.7
1       62          NaN      1.0    NaN
2      278          NaN      1.0    NaN
3      452          NaN      1.0    NaN
4      454          NaN      1.0    NaN
5      473          NaN      1.0    NaN
6     1270          NaN      1.0    NaN
7     2154          NaN      1.0    NaN
8     2155          NaN      1.0    NaN
9     4458          NaN      1.0    NaN

In [50]:
mse = mean_squared_error(y_true=result_df['score'].values, y_pred=result_df['pred_rating'].values)
rmse = np.sqrt(mse)

print(mse, rmse)

ValueError: Input contains NaN.

## scores(ratings) NaN값으로 불가

##